# Generated by Django 2.2.3 on 2019-07-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pride',
            new_name='price',
        ),
    ]
